"""add_indexes_to_weather_requests

Revision ID: 9c4638e88f37
Revises: c8230f910640
Create Date: 2026-05-19 12:02:40.966379

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c4638e88f37"
down_revision: Union[str, Sequence[str], None] = "c8230f910640"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_city_timestamp", "weather_requests", ["city", "timestamp"], unique=False
    )
    op.create_index("idx_timestamp", "weather_requests", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_timestamp", table_name="weather_requests")
    op.drop_index("idx_city_timestamp", table_name="weather_requests")
    # ### end Alembic commands ###
