"""Initial migration

Revision ID: c8230f910640
Revises: 
Create Date: 2026-05-18 13:41:05.197173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8230f910640'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('units', sa.String(length=1), nullable=False),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_requests_city'), 'weather_requests', ['city'], unique=False)
    op.create_index(op.f('ix_weather_requests_id'), 'weather_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_requests_id'), table_name='weather_requests')
    op.drop_index(op.f('ix_weather_requests_city'), table_name='weather_requests')
    op.drop_table('weather_requests')
    # ### end Alembic commands ###
